tnct-spc/GulliverBlocksApp

Assets/CameraMover.cs, Assets/CameraMover.cs.meta, Assets/Scenes/Game.unity, ProjectSettings/ProjectSettings.asset
前に進むボタン[17](https://trello.com/c/PJ9uVYaZ/17-%E5%89%8D%E3%81%AB%E9%80%B2%E3%82%80%E3%83%9C%E3%82%BF%E3%83%B3)に対するPRです．
- CameraMover.csと追加した．
- MoveForwardボタンを作った．
- MoveForwardボタンを押したらカメラが正面に動くようにした．
unity初心者のため書き方が汚いと思うのでレビューをお願いします．
あと，実機がなくてテストができていないのでどなたか実機を貸してください．(エミュではテスト済み)
=> [add]前に進む機能を追加した

ProjectSettings/ProjectSettings.asset
-ドメイン名を「tokyo-ct.org」に変更
-
-
特記事項あれば
=> 21[add]ドメイン名を変更

Assets/TitleScenes/Scripts/GameSystem.cs
タスク[27](feature/27/fixed-screen)に対するPRです。
-端末の向きが変わっても画面の向きが変わらないようにしました。
-
-
特記事項あれば
=> 端末の向きが変わっても、画面の向きが変わらないようにしました。

Assets/VrScenes/Scripts/BlockManager.cs
タスク[15](https://trello.com/c/KuWfdUUR/15-%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC%E3%81%8B%E3%82%89%E3%83%87%E3%83%BC%E3%82%BF%E3%82%92%E5%8F%96%E3%81%A3%E3%81%A6%E3%81%8D%E3%81%A6%E5%8F%8D%E6%98%A0)に対するPRです。
- BlockManagerにJsonToBlock関数とgetDataFromServerAndCreateBlock関数を追加した
- Block構造体にjsonと同じメンバ変数を追加
- Block構造体のpositionはgetPosition関数で生成して渡すようにした
- テストデータのjson構造を[これのコメント欄](https://trello.com/c/gxKArLQq/81-testdata%E3%81%AEjson%E3%81%AE%E6%A7%8B%E9%80%A0%E3%82%92%E5%A4%89%E3%81%88%E3%82%8B)の通りに変更した
起動してからブロックの生成までに少し時間(3sぐらい)がかかります
=> [add]テストサーバーからのデータをもとにブロックを生成する

Assets/VrScenes/Scripts/PlayerManager.cs
タスク[82](https://trello.com/c/t3JCwp9t/82-bug%E7%A7%BB%E5%8B%95%E3%81%AE%E3%81%A8%E3%81%8D%E3%81%AB%E4%B8%8A%E4%B8%8B%E6%96%B9%E5%90%91%E3%81%AB%E5%8A%9B%E3%81%8C%E5%83%8D%E3%81%84%E3%81%A6%E3%81%97%E3%81%BE%E3%81%A3%E3%81%A6%E3%81%84%E3%82%8B)に対するPRです。
- Velocityのy要素を常に0にするようにした
=> [fix]上方向に移動しないようにした

Assets/SettingScene.meta, Assets/SettingScene/Scripts.meta, Assets/SettingScene/Scripts/MoveScene.cs, Assets/SettingScene/Scripts/MoveScene.cs.meta, Assets/SettingScene/SettingScene.unity, Assets/SettingScene/SettingScene.unity.meta, Assets/TitleScenes/Scripts/GameSystem.cs, Assets/TitleScenes/Title.unity, Assets/TouchScript/Examples/_misc/Textures/Icons.meta, ProjectSettings/EditorBuildSettings.asset
73[add]settingsceneの作成
-設定画面を作りました
-
-
特記事項あれば
=> settigsceneの作成

Assets/VrScenes/Scripts/BlockManager.cs
タスク[108](https://trello.com/c/hlBcDK1E/108-%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC%E4%BB%95%E6%A7%98%E5%A4%89%E6%9B%B4-%E3%83%8F%E3%83%BC%E3%83%89%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E3%81%A7%E5%AF%BE%E5%BF%9C)に対するPRです。
-
-
-
特記事項あれば
=> 108 [hotfix] サーバーの仕様変更に伴う一時的な対応

Assets/VrScenes/Scripts/BlockManager.cs
タスク[131](https://trello.com/c/kBBlgR9i/129-%E3%83%96%E3%83%AD%E3%83%83%E3%82%AF%E3%82%92%E3%82%BF%E3%83%83%E3%83%97%E3%81%97%E3%81%9F%E3%82%89%E3%81%9D%E3%81%AE%E3%83%96%E3%83%AD%E3%83%83%E3%82%AF%E3%81%AE%E8%89%B2%E3%82%92%E5%A4%89%E3%81%88%E3%82%8B%E3%83%A1%E3%83%8B%E3%83%A5%E3%83%BC%E3%82%92%E4%BD%9C%E3%82%8B)に対するPRです。
- typoを修正しました。
=> 131[fix]typoの修正

Assets/VrScenes/Scripts/BlockManager.cs, Assets/VrScenes/Vr.unity
ブロックが配置されるまでローディング画面を表示する[147](https://trello.com/c/0HO0ewK8/147-%E3%83%96%E3%83%AD%E3%83%83%E3%82%AF%E3%81%8C%E9%85%8D%E7%BD%AE%E3%81%95%E3%82%8C%E3%82%8B%E3%81%BE%E3%81%A7%E3%83%AD%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E7%94%BB%E9%9D%A2%E3%82%92%E8%A1%A8%E7%A4%BA%E3%81%99%E3%82%8B)に対するPRです。
-ブロックが読み込まれている間ローディング画面が表示されるようにしました。
=> 147[add]ブロックが配置されるまでローディング画面を表示する

Assets/VrScenes/Scripts/PlayerManager.cs
タスク94に対するPRです。
-プレイヤーがワールドから落ちたときにリスポーンするようにした
-
-
特記事項あれば
=> [add] resporn

Assets/Project/Script/CommunicationManager.cs, Assets/Project/VrScenes/Scripts/IncludingBlockInfo.cs
=> [hotifx] conflict解消時に座標に係数を掛ける処理が抜けていた

Assets/Project/VrScenes/Scripts/BlockManager.cs
=> [fix]applycolorrulesのtargetIDを修正

Assets/Project/Script/CommunicationManager.cs, Assets/Project/Script/UnityWebRequestAwaiter.cs, Assets/Project/Script/UnityWebRequestAwaiter.cs.meta, Assets/Project/TitleScenes/Scripts/WorldSelect.cs, Assets/Project/VrScenes/Scripts/BlockManager.cs, Assets/TitleScenes.meta, Assets/TitleScenes/Scripts.meta
タスク[125](https://trello.com/c/7aJDRz30/125-communicationmanager%E4%BD%9C%E6%88%90)に対するPRです。
-
-
-
特記事項あれば
=> 125[update] CommunicationManagerでリクエストを叩くように

Assets/Project/VrScenes/Scripts/PlayerManager.cs
=> [hotfix] 2眼VRにしたときにPlayerが回転してしまう問題

Assets/Project/VrScenes/Scripts/BlockManager.cs
183[fix](TrelloのタスクURL)に対するPRです。
-UnityでVRシーンから直接起動できるようにしました
-
-
特記事項あれば
=> [fix]UnityでVRシーンから直接起動できるようにした

Assets/Project/VrScenes/Scripts/BlockManager.cs, Assets/Resources/Materials.meta, Assets/Resources/Materials/Metal.mat, Assets/Resources/Materials/Metal.mat.meta, Assets/TitleScenes.meta
タスク179に対するPRです。
-change color by id 
-
-
特記事項あれば
=> [add] change color by id

Assets/Resources/Color12.mat, Assets/Resources/Color12.mat.meta
=> [ADD]white color material

Assets/Project/VrScenes/Scripts/InputManager.cs, Assets/Project/VrScenes/Vr.unity, Assets/TitleScenes/Scripts.meta
再生モード、再生中は他のUIを消す[211](https://trello.com/c/a4irlse5/211-%E5%86%8D%E7%94%9F%E3%83%A2%E3%83%BC%E3%83%89%E3%80%81%E5%86%8D%E7%94%9F%E4%B8%AD%E3%81%AF%E4%BB%96%E3%81%AEui%E3%82%92%E6%B6%88%E3%81%99)に対するPRです。
- playbackボタンを押したら他のUIが消えるようにした
-
-
特記事項あれば
=> 再生中は他のUIが消えるようにした

Assets/Project/VrScenes/Scripts/InputManager.cs, Assets/Project/VrScenes/Scripts/PlayerManager.cs, Assets/Project/VrScenes/Vr.unity
generalメニューをつくる[217](https://trello.com/c/xARirLBa/217-general%E3%83%A1%E3%83%8B%E3%83%A5%E3%83%BC%E3%82%92%E3%81%A4%E3%81%8F%E3%82%8B)に対するPRです。
- generalmenuを作った
- Vrbuttonの位置を変えた
-
特記事項あれば
=> general menuを作る

ProjectSettings/ProjectSettings.asset
タスク[228](https://trello.com/c/l7CqY50p/228-%E3%83%95%E3%83%AB%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3%E8%A1%A8%E7%A4%BA%E3%81%99%E3%82%8B%E3%82%88%E3%81%86%E3%81%AB%E3%81%99%E3%82%8B)に対するPRです。
-
-
-
特記事項あれば
=> [fix] 起動時デフォルトでフルスクリーン表示するように

Assets/Project/MergeScenes/Merge.unity, Assets/Project/MergeScenes/Script/InputManager.cs, Assets/Project/SettingScene/SettingScene.unity, Assets/Project/TitleScenes/Scripts/GameSystem.cs, Assets/Project/TitleScenes/Scripts/WorldSelect.cs, Assets/Project/TitleScenes/Title.unity, Assets/Project/TitleScenes/UI.meta, Assets/Project/TitleScenes/UI/BackButton.prefab, Assets/Project/TitleScenes/UI/BackButton.prefab.meta, Assets/Project/VrScenes/Vr.unity
全ての画面に戻るボタンを追加する[212](https://trello.com/c/B6lzTHjq/212-%E5%85%A8%E3%81%A6%E3%81%AE%E7%94%BB%E9%9D%A2%E3%81%AB%E6%88%BB%E3%82%8B%E3%83%9C%E3%82%BF%E3%83%B3%E3%82%92%E8%BF%BD%E5%8A%A0%E3%81%99%E3%82%8B)に対するPRです。
- すべてのUIに戻るボタンを追加
-
-
特記事項あれば
=> back buttonをつくる

Assets/Project/SettingScene/Scripts/SaveUsername.cs, Assets/Project/SettingScene/Scripts/SaveUsername.cs.meta, Assets/Project/SettingScene/SettingScene.unity
タスク[141](https://trello.com/c/fWxh4v8M/141-playerprefs%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%A6%E5%90%84%E7%A8%AE%E8%A8%AD%E5%AE%9A%E3%82%92%E4%BF%9D%E5%AD%98%E3%81%99%E3%82%8B%E3%82%88%E3%81%86%E3%81%AB)に対するPRです。
設定画面にユーザー名をセーブ、ロード、削除できるようにしました。
=> 141[add]PlayerPrefsを使って各種設定を保存するように

Assets/Project/Script/CommunicationManager.cs, Assets/Project/VrScenes/Scripts/BlockManager.cs
タスク[216](https://trello.com/c/UtL49dUJ/216-websocket-timeout)に対するPRです。
-
-
-
特記事項あれば
=> 216[fix] websocketが60秒で切れる問題

Assets/Project/VrScenes/Scripts/ColorChangePanel.cs
タスク[186](TrelloのタスクURL)に対するPRです。
-
-
-
特記事項あれば
=> 186[fix]ブロックの選択をキャンセルしたら光らないようにした

Assets/Project/VrScenes/Scripts/BlockManager.cs
タスク[206](https://trello.com/b/lqshHZlQ/gulliverblocks)に対するPRです。
-  再生モードで置かれた時間がほぼ同じブロックは同時に生成されるように変更しました。
=> 206[update]ブロックの配置 ほぼ同じ時間に配置されたものは同時に配置する

Assets/Project/VrScenes/Scripts/HorizontalRoadManager.cs, Assets/Project/VrScenes/Scripts/VerticalRoadManager.cs
=> [fix]car speed

Assets/Project/VrScenes/Vr.unity
タスク[308](TrelloのタスクURL)に対するPRです。
-目線の高さを変更しました。
-
-
特記事項あれば
=> 308[fix]目線変更

Assets/Plugins/Android.meta, Assets/Plugins/Android/BugsnagUnity.Android.dll.meta, Assets/Plugins/Android/bugsnag-android-ndk-release.aar.meta, Assets/Plugins/Android/bugsnag-android-release.aar.meta, Assets/Plugins/Android/bugsnag-android-unity-release.aar.meta, Assets/Plugins/Android/mainTemplate.gradle.DISABLED.meta, Assets/Project/SettingScene/SettingScene.unity
タスク[310](TrelloのタスクURL)に対するPRです。
-
-
-
特記事項あれば
=> 設定画面でUIが被らないようにした

Assets/Project/Script/CommunicationManager.cs, Assets/Project/TitleScenes/Scripts/GameSystem.cs, Assets/Simple Buttons/Icons.meta, Assets/TitleScenes/Scripts.meta
タスク[301](https://trello.com/c/5Aq1LuKE/301-world%E4%BD%9C%E6%88%90%E3%81%A7%E3%81%8D%E3%82%8B%E3%82%88%E3%81%86%E3%81%AB%E3%81%99%E3%82%8B)に対するPRです。
-
-
-
特記事項あれば
=> [add] World新規作成できるように

Assets/Project/MergeScenes/Script/MapParent.cs
=> [hotifx] mergeが動いてなかった

Assets/Project/VrScenes/Scripts/BlockManager.cs
タスク[337](https://trello.com/c/nGM7LkXj/337-%E9%81%93%E8%B7%AF-%E3%83%90%E3%82%B0)に対するPRです。
- ブロックの追加時と，削除時にパターンを更新するようにした
まだバグがあるんですけど，developよりマシになると思います．
=> [fix]ブロックの追加時と，削除時にパターンを更新するようにした

Assets/Project/VrScenes/Scripts/BlockManager.cs
タスク[353](https://trello.com/c/z5T9huqS/353-%E5%86%8D%E7%94%9F%E3%83%A2%E3%83%BC%E3%83%89-%E3%83%90%E3%82%B0)に対するPRです。
-
-
-
特記事項あれば
=> [fix] 353 websocketで送られてきたブロックの再生がうまくいかない問題

Assets/Project/VrScenes/Scripts/BlockManager.cs
=> Fix/337 2/pattern delete

Assets/Project/VrScenes/Scripts/BlockManager.cs
=> [fix]パターン構成ブロックが一つでも消えたらパターンも消えるようにした

Assets/Project/VrScenes/Vr.unity
=> [fix]日本語を修正
