Assets/Scenes/Game.unity, Assets/Scripts/gryo.cs, Assets/Scripts/gryo.cs.meta
Gameシーンを加速度センサーでぐるぐるできるように[4](https://trello.com/c/Xv8AKlSj/4-game%E3%82%B7%E3%83%BC%E3%83%B3%E3%82%92%E5%8A%A0%E9%80%9F%E5%BA%A6%E3%82%BB%E3%83%B3%E3%82%B5%E3%83%BC%E3%81%A7%E3%81%90%E3%82%8B%E3%81%90%E3%82%8B%E3%81%A7%E3%81%8D%E3%82%8B%E3%82%88%E3%81%86%E3%81%AB)に対するPRです。
- main cameraにgryoという角度をジャイロセンサーで変えられるスクリプトを追加した。
-
-
特記事項あれば
=> [add]カメラの角度をジャイロセンサーで動かせるようにした

.gitignore, Assets/VrScenes/Vr.unity
タスク[31](https://trello.com/c/oAeVX16q/45-%E3%83%97%E3%83%AC%E3%82%A4%E3%83%A4%E3%83%BC%E3%81%AB%E5%BD%93%E3%81%9F%E3%82%8A%E5%88%A4%E5%AE%9A%E3%82%92%E3%81%A4%E3%81%91%E3%82%8B-31)に対するPRです。
- VrScenesのMainCameraの名前をPlayerに変更
- PlayerにCapsule Colliderを追加
- PlayerのRigidBobyのUseGravityをONにした
- Playerの元の初期位置だと重力で奈落に落下してしまうため，初期位置をx:0, y:1, z:0にした
=> [add]新しいadd除外ファイル, Playerに当たり判定

Assets/TitleScenes/Title.unity, Assets/VrScenes/Vr.unity
タスク[23](https://trello.com/c/hfPojxC5/23-ui%E3%81%AE%E5%A4%A7%E3%81%8D%E3%81%95%E3%82%92%E3%81%A9%E3%82%93%E3%81%AA%E7%AB%AF%E6%9C%AB%E3%81%A7%E8%A6%8B%E3%81%A6%E3%82%82%E5%95%8F%E9%A1%8C%E3%81%AA%E3%81%84%E3%82%88%E3%81%86%E3%81%AB%E3%81%99%E3%82%8B)に対するPRです。
-Hierarchy=>Canvas(or TitleWindow)=>Canvas Scaler(script)=>UI Scale ModeをConstant Pixel Sizeから Scale With Screen Sizeに変更  
-ボタン及びボタンに重なったテキストのサイズをスマートフォンで押しやすいサイズに変更
=> 23[add]UIの大きさをどんな端末で見ても問題ないようにした

Assets/TitleScenes/Scripts/BugsnagInit.cs.meta, Assets/VrScenes/Scripts/GameManager.cs, Assets/VrScenes/Scripts/GameManager.cs.meta, Assets/VrScenes/Scripts/InputManager.cs, Assets/VrScenes/Vr.unity
タスク[59](https://trello.com/c/HmRJUw9w/59-vr%E3%82%B7%E3%83%BC%E3%83%B3%E3%81%8B%E3%82%89title%E3%82%B7%E3%83%BC%E3%83%B3%E3%81%ABandroid%E3%81%AE%E6%88%BB%E3%82%8B%E3%83%9C%E3%82%BF%E3%83%B3%E3%81%A7%E6%88%BB%E3%82%8C%E3%82%8B%E3%82%88%E3%81%86%E3%81%AB)に対するPRです。  
- VR SceneでAndroidの戻るボタンが押されるとTitle Sceneに戻るようにした  
- GameSystemオブジェクトにGameManager.csをコンポーネントとして追加  
- GameManager.cs内の関数をInputManager.csから呼び出すようにした
=> 59[add]Androidの戻るボタンでTitle Sceneに戻るようにした

Assets/TitleScenes/Scripts/BugsnagInit.cs.meta, Assets/TouchScript/Editor/EditorResources/Icons.meta, Assets/TouchScript/Examples/_misc/Textures/Icons.meta, Assets/VrScenes/Scripts/InputManager.cs, Assets/VrScenes/Scripts/PlayerManager.cs, Assets/VrScenes/Vr.unity
タスク[96](https://trello.com/c/cd4y2KZa/96-51%E7%A7%BB%E5%8B%95%E6%96%B9%E5%90%91%E3%81%AE%E5%AE%9F%E8%A3%85%E6%96%B9%E6%B3%95%E3%82%92%E5%A4%89%E6%9B%B4%E3%81%99%E3%82%8B)に対するPRです。
-移動に関する処理を従来のMove_Stateを読み取る形から直接Vector3の数値を増減させる形に変更しました。
-これにより、ボタンの同時押しによる斜め移動が可能になりました。
-
特記事項あれば
=> 96[update](51)移動方向の実装方法を変更する

Assets/TitleScenes/Scripts/GameSystem.cs, Assets/TouchScript/Examples/_misc/Textures/Icons.meta
タスク[133](https://trello.com/c/3YXgk69M/133-%E3%83%AF%E3%83%BC%E3%83%AB%E3%83%89%E9%81%B8%E6%8A%9E%E7%94%BB%E9%9D%A2-android%E3%81%AE%E6%88%BB%E3%82%8B%E3%83%9C%E3%82%BF%E3%83%B3%E3%81%A7%E6%88%BB%E3%82%8C%E3%82%8B%E3%82%88%E3%81%86%E3%81%AB%E3%81%99%E3%82%8B)に対するPRです。
- Titleシーンでワールド選択画面を開いている時にAndroidの戻るボタンを押すと、ワールド選択画面が非表示になり初期状態に戻るようにしました。
=> 133[update]ワールド選択画面 Androidの戻るボタンで戻れるようにする

Assets/Project/TitleScenes.meta, Assets/Project/VrScenes/Scripts/InputManager.cs, Assets/Project/VrScenes/Vr.unity, Assets/TitleScenes.meta, Assets/TitleScenes/Scripts.meta
2元表示中は他のボタンを表示しないようにする[145](https://trello.com/c/bgUbV0kj/145-2%E5%85%83%E8%A1%A8%E7%A4%BA%E4%B8%AD%E3%81%AF%E4%BB%96%E3%81%AE%E3%83%9C%E3%82%BF%E3%83%B3%E3%82%92%E8%A1%A8%E7%A4%BA%E3%81%97%E3%81%AA%E3%81%84%E3%82%88%E3%81%86%E3%81%AB%E3%81%99%E3%82%8B)に対するPRです。
-二眼モードに切り替えた時には各種UIが非表示になるようにしました。
=> 145[update]2元表示中は他のボタンを表示しないようにする

Assets/Project/VrScenes/Scripts/InputManager.cs
2元表示中は他のボタンを表示しないようにする[145](https://trello.com/c/bgUbV0kj/145-2%E5%85%83%E8%A1%A8%E7%A4%BA%E4%B8%AD%E3%81%AF%E4%BB%96%E3%81%AE%E3%83%9C%E3%82%BF%E3%83%B3%E3%82%92%E8%A1%A8%E7%A4%BA%E3%81%97%E3%81%AA%E3%81%84%E3%82%88%E3%81%86%E3%81%AB%E3%81%99%E3%82%8B)に対するPRです。
-二眼モードから通常モードに切り替えた時にボタンが再表示されなかったバグを修正しました。
=> 145[fix]2元表示中は他のボタンを表示しないようにする

Assets/Project/SettingScene/Scripts/SettingManager.cs, Assets/Project/SettingScene/Scripts/SettingManager.cs.meta, Assets/Project/SettingScene/SettingScene.unity, Assets/Project/VrScenes/Scripts/PlayerManager.cs, Assets/Project/VrScenes/Vr.unity, Assets/TitleScenes/Scripts.meta
顔の向きの変更を [タッチのみ] + [タッチ + ジャイロ]で切り替えられるようにする[199](https://trello.com/c/bKnUBBJx/199-%E9%A1%94%E3%81%AE%E5%90%91%E3%81%8D%E3%81%AE%E5%A4%89%E6%9B%B4%E3%82%92-%E3%82%BF%E3%83%83%E3%83%81%E3%81%AE%E3%81%BF-%E3%82%BF%E3%83%83%E3%83%81-%E3%82%B8%E3%83%A3%E3%82%A4%E3%83%AD%E3%81%A7%E5%88%87%E3%82%8A%E6%9B%BF%E3%81%88%E3%82%89%E3%82%8C%E3%82%8B%E3%82%88%E3%81%86%E3%81%AB%E3%81%99%E3%82%8B)に対するPRです。
-設定シーンからジャイロのオンオフを切り替えられるようにしました。
=> 199[add]顔の向きの変更を [タッチのみ] + [タッチ + ジャイロ]で切り替えられるようにする

Assets/Project/VrScenes/Scripts/PlayerManager.cs, Assets/Project/VrScenes/Vr.unity, Assets/TitleScenes.meta
タスク[190](https://trello.com/c/cjAU0p8v/190-bug-%E3%83%96%E3%83%AD%E3%83%83%E3%82%AF%E3%81%AE%E9%81%B8%E6%8A%9E%E7%94%BB%E9%9D%A2%E3%81%AE%E3%82%B9%E3%82%AF%E3%83%AD%E3%83%BC%E3%83%AB%E3%81%A7%E7%94%BB%E9%9D%A2%E3%81%8C%E5%9B%9E%E3%81%A3%E3%81%A6%E3%81%97%E3%81%BE%E3%81%86%E3%81%93%E3%81%A8%E3%81%8C%E3%81%82%E3%82%8B)に対するPRです。
- VrSceneの色選択画面をタップ、ドラッグした際に視点が移動してしまう問題を修正しました。
=> 190[fix]ブロックの選択画面のスクロールで画面が回ってしまうことがある

Assets/Project/VrScenes/Scripts/BlockManager.cs, Assets/Project/VrScenes/Vr.unity, Assets/Resources/Floor2.prefab
タスク[268](https://trello.com/c/3YgiB1Jo/268-floor-%E8%A6%AA%E3%82%92%E4%BD%9C%E3%81%A3%E3%81%A6%E3%81%9D%E3%81%AE%E4%B8%AD%E3%81%AB%E7%94%9F%E6%88%90%E3%81%99%E3%82%8B%E3%82%88%E3%81%86%E3%81%AB%E3%81%99%E3%82%8B)に対するPRです。
- 床ブロックを生成する際、Vrシーンに新しく追加した空オブジェクトの子オブジェクトとして生成されるように変更しました。
- タスクの内容には入っていませんが、前回私がやったブロックをコードで生成するタスク以来、平面ブロックの位置がずれていた関係でプレイヤーが床に半分沈んでしまっていたので、そちらの問題も修正しました。
=> 268[update]floor, 親を作ってその中に生成するようにする

Assets/Project/Script/CommunicationManager.cs, Assets/Project/VrScenes/Scripts/BlockManager.cs, Assets/Project/VrScenes/Scripts/ColorChangePanel.cs
ブロックの色をスマホで変えたときに変更をサーバーに保存する[191](https://trello.com/c/4DM7Jb53/191-%E3%83%96%E3%83%AD%E3%83%83%E3%82%AF%E3%81%AE%E8%89%B2%E3%82%92%E3%82%B9%E3%83%9E%E3%83%9B%E3%81%A7%E5%A4%89%E3%81%88%E3%81%9F%E3%81%A8%E3%81%8D%E3%81%AB%E5%A4%89%E6%9B%B4%E3%82%92%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC%E3%81%AB%E4%BF%9D%E5%AD%98%E3%81%99%E3%82%8B)に対するPRです。
- colorchangepanel.csをいじった
-
-
特記事項あれば
=> ブロックの色をスマホで変えたときに変更をサーバーに保存する

Assets/Project/VrScenes/Scripts/BlockManager.cs, Assets/Project/VrScenes/Scripts/PlayerManager.cs, Assets/Project/VrScenes/Vr.unity, Assets/Resources/Floor1.prefab, Assets/Resources/Floor2.prefab
タスク[283](https://trello.com/c/t8IURwtB/283-%E5%BA%8A%E3%81%AE%E9%AB%98%E3%81%95%E3%81%8C%E9%96%93%E9%81%95%E3%81%A3%E3%81%A6%E3%81%84%E3%82%8B)に対するPRです。
- 床の高さをy=0に変更しました。
- リスポーンする高度を床の高度に合わせて変更しました。
- Block2(平面オブジェクト)の面積を0.32x0.32(ブロックの面積と同じ)に微調整しました。
=> 283[update]床の高さが間違っている

Assets/Project/VrScenes/Scripts/Block.cs, Assets/Project/VrScenes/Scripts/BlockManager.cs, Assets/Project/VrScenes/Scripts/ColorChangePanel.cs, Assets/Project/VrScenes/Vr.unity
ColorRuleがn重に適用される[278](https://trello.com/c/vXmY2KMq/278-colorrule%E3%81%8Cn%E9%87%8D%E3%81%AB%E9%81%A9%E7%94%A8%E3%81%95%E3%82%8C%E3%82%8B)に対するPRです。
- Block.csにapplied_colorIDを追加
- 元々の色を基準にしてcolorruleを適用するようにした
-
特記事項あれば
=> 元々の色を基準にしてcolorruleを適用するようにした

Assets/Project/VrScenes/Scripts/BlockManager.cs, Assets/Project/VrScenes/Vr.unity, Assets/Simple Buttons/Icons.meta, Assets/TitleScenes/Scripts.meta
マージしたときマージした部分の床を生成するようにする[265](https://trello.com/c/znHWh5T1/265-%E3%83%9E%E3%83%BC%E3%82%B8%E3%81%97%E3%81%9F%E3%81%A8%E3%81%8D%E3%83%9E%E3%83%BC%E3%82%B8%E3%81%97%E3%81%9F%E9%83%A8%E5%88%86%E3%81%AE%E5%BA%8A%E3%82%92%E7%94%9F%E6%88%90%E3%81%99%E3%82%8B%E3%82%88%E3%81%86%E3%81%AB%E3%81%99%E3%82%8B)に対するPRです。
- blockの座標に合わせてfloorを配置するようにした
- playerをy=20でスポーンさせるようにした
-
特記事項あれば
=> マージしたときマージした部分の床を生成するようにする

Assets/Project/VrScenes/Vr.unity
タスク[298](https://trello.com/c/zyrmg7zV/298-vr%E3%81%A7%E8%BF%91%E3%81%8F%E3%81%AE%E3%82%82%E3%81%AE%E3%81%8C%E9%80%8F%E3%81%91%E3%81%A6%E3%81%97%E3%81%BE%E3%81%86%E5%95%8F%E9%A1%8C)に対するPRです。
-
-
-
特記事項あれば
=> 298 [fix] 2眼VRにしたときに近くの物が透けてしまう問題

Assets/Project/TitleScenes/Scripts/GameSystem.cs, ProjectSettings/ProjectSettings.asset
タスク[172](https://trello.com/c/MFmV9Cx9/172-title%E7%94%BB%E9%9D%A2%E3%81%A72%E7%9C%BCvr%E3%81%AB%E3%81%AA%E3%81%A3%E3%81%A6%E3%81%97%E3%81%BE%E3%81%86)に対するPRです。
-
-
-
特記事項あれば
=> [fix] 2眼VRの状態で起動してしまう問題

Assets/Project/VrScenes/Scripts/BlockManager.cs
タスク[326](https://trello.com/c/InAUEIPg/326-%E3%83%91%E3%82%BF%E3%83%BC%E3%83%B3%E8%AA%8D%E8%AD%98%E9%81%93%E8%B7%AF-%E6%B5%AE%E3%81%84%E3%81%A6%E3%82%8B)に対するPRです。
- 割り算で小数点以下が切り捨てされる実装になっていたので直した
=> [fix]道路が浮いてる

Assets/Project/VrScenes/Scripts/BlockManager.cs, Assets/Project/VrScenes/Scripts/InputManager.cs, Assets/Resources/RoadMaterialImage.png.meta, Assets/SocialConnector/Plugins/Android.meta
タスク[292](TrelloのタスクURL)に対するPRです。
- 再生モードをオンにするとブロックがあらかじめ落下開始地点にテレポートするようになりました。(若干のラグ軽減)
- 再生モードでブロックが落下しきるまで再生が続くようになりました
- 同時に落下するブロックの範囲を±1秒に変更しました。(現実でブロックを置いて作成したマップでの動作は未確認なので要検証)
- 同時に落下するブロックを1つの親オブジェクトにまとめることが出来ればさらにラグを改善できますが、当日までに間に合うかどうかが怪しいので一旦現状進めた部分だけマージをお願いします。
=> 292[update]再生、若干ラグがある

Assets/Project/VrScenes/Scripts/BlockManager.cs, Assets/Project/VrScenes/Vr.unity, Assets/Resources/Wall.prefab, Assets/Resources/Wall.prefab.meta, Assets/Resources/WallMaterial.mat, Assets/Resources/WallMaterial.mat.meta
マージしたときマージした部分の床を生成するようにする ＋ 見えない壁[265](https://trello.com/c/znHWh5T1/265-%E3%83%9E%E3%83%BC%E3%82%B8%E3%81%97%E3%81%9F%E3%81%A8%E3%81%8D%E3%83%9E%E3%83%BC%E3%82%B8%E3%81%97%E3%81%9F%E9%83%A8%E5%88%86%E3%81%AE%E5%BA%8A%E3%82%92%E7%94%9F%E6%88%90%E3%81%99%E3%82%8B%E3%82%88%E3%81%86%E3%81%AB%E3%81%99%E3%82%8B-%EF%BC%8B-%E8%A6%8B%E3%81%88%E3%81%AA%E3%81%84%E5%A3%81)に対するPRです。
-マップの端に見えない壁を追加しました。
-マージされたマップの床の大きさがブロックの位置に合わせて変わるようにしました。
-処理上、床が生成されるのが遅れてしまい、タイミングによっては床やブロックに埋まってスタックしてしまうので、スポーン地点付近に見えない床を設置しました。
通常のマップでの壁の大きさは正確ですが、マージされたマップの床の大きさは処理上、-X方向と-Z方向の壁は正確に配置できますがX,Z方向は床の大きさよりも壁の大きさが大きくなってしまう事が多々あったので、それらの方向の壁は遊びを持たせて配置してあります。
また、直接は関係ないですが現在自分の環境だとマージマップの作成がdevelopでも上手くできないです。(今回のタスクは通常のマップを一時的にマージマップ判定で処理を行わせて開発しました。)此方に問題があるかもしれませんが一応報告させて頂きます。
=> 265[update]マージしたときマージした部分の床を生成するようにする ＋ 見えない壁
